version: '3.9'
services:
  postgres:
    image: postgis/postgis:latest # Altere para a imagem PostGIS
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: geodb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/seeds/dados-semente.sql:/docker-entrypoint-initdb.d/dados-semente.sql  # Se você tiver um script de inicialização
      - ./init_postgis.sh:/docker-entrypoint-initdb.d/init_postgis.sh  # Script de inicialização para ativar o PostGIS (opcional)
    
  nest_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      DB_NAME: geodb
    volumes:
      - .:/app
    depends_on:
      - postgres

volumes:
  postgres_data:
