services:
  postgres:
    image: postgis/postgis:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/seeds/dados-semente.sql:/docker-entrypoint-initdb.d/dados-semente.sql
      - ./init_postgis.sh:/docker-entrypoint-initdb.d/init_postgis.sh
 
  nest_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/app
    depends_on:
      - postgres

volumes:
  postgres_data:
